name: "Security Scan (End of life and Outdated JS)"
description: "Reusable composite action for scanning dependencies for end-of-life and outdated JS packages."

inputs:
  token:
    description: "GitHub token for creating/updating comments"
    required: true
  project:
    description: "Project name for dependency-check"
    required: true
  path:
    description: "Path to run dependency-check on"
    required: false
    default: "."
  suppression_file:
    description: "Path to the suppression.xml file"
    required: false
    default: "suppression.xml"

runs:
  using: "composite"
  steps:
    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        path: ${{ inputs.path }}
        format: 'JSON'
        project: ${{ inputs.project }}
        args: >
          --failOnCVSS 7
          --exclude "**/node_modules/**"
          --exclude "**/bower_components/angular*/**"
          --suppression ${{ inputs.suppression_file }}

    - name: Run dependency-check script to generate comment
      if: ${{ !cancelled() }}
      shell: bash
      id: generate_comment
      run: |
        # Run your Node script and capture the output into comment.txt
        node generate-comment.js > comment.txt
        # Output the comment body for later steps
        echo "comment<<EOF" >> $GITHUB_OUTPUT
        cat comment.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Find existing dependency check comment
      if: ${{ !cancelled() }}
      id: find_comment
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: 'Security Scan Results'
        comment-author: 'github-actions[bot]'

    - name: Create dependency check comment
      if: ${{ steps.find_comment.outputs.comment-id == '' && !cancelled() }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.generate_comment.outputs.comment }}

    - name: Update dependency check comment
      if: ${{ steps.find_comment.outputs.comment-id != '' && !cancelled() }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.generate_comment.outputs.comment }}
        edit-mode: 'replace'
